name: influx
base: core18
version: __VERSION__
summary: InfluxDB Client
description: |
  Commandline client for interacting with InfluxDB

grade: devel
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: arm64


parts:
  influx:
    plugin: dump
    source: bin/


apps:
  influx:
    command: env INFLUX_CONFIGS_PATH=$SNAP_USER_DATA/configs $SNAP/influx
    plugs:
      - home
      - removable-media
      - network


